apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: {{ .Values.image.port }}
  selector:
    app: {{ .Values.image.name }}
  type: {{ .Values.service.type }}
